Testing
YunoHost-Apps/ampache_ynh pull request #86
Opened 2022-05-19 05:28 UTC by ericgaspar

## Problem
- *Description of why you made this PR*

## Solution
- *And how do you fix that problem*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

2022-05-19 05:28 UTC, ericgaspar commented
!testme

2022-05-20 05:10 UTC, ericgaspar commented
!testme

2022-05-21 09:43 UTC, yalh76 requested changes

2022-05-21 09:43 UTC, yalh76 commented on scripts/install
> +ynh_app_setting_set --app=$app --key=phpversion --value=$phpversion
why setting `phpversion`, it's already set in ynh_add_fpm_config ?

2022-05-21 09:43 UTC, yalh76 commented on scripts/install
> +phpversion=$YNH_PHP_VERSION
I don't think we need to do that

2022-05-21 09:49 UTC, ericgaspar commented
!testme

2022-05-21 10:18 UTC, yalh76 commented on scripts/install
> +ynh_app_setting_set --app=$app --key=phpversion --value=$phpversion
maybe, we will need `phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)`

2022-05-23 18:03 UTC, yalh76 approved these changes

2022-05-23 18:45 UTC, merged